name: Generate Schema

on: workflow_dispatch
      
jobs:
  generateSchema:
  
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
    
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Generate schema
        run: deno task schema
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: generate schema
          title: Generate schema
          body: Generate GraphQL schema in `schema.ts`
          branch: schema
